### PR TITLE
Uploading new sunpy sample data files - v2

### PR DESCRIPTION
**Pull request by aringlis**
This PR replaces old mismatched SunPy sample data files with a consistent set of files from a particular solar flare event on 2011-06-07.

### CODE REVIEW

**Comment by aringlis** [comment]
This sample file folder should be complete now, except for:
    - a RHESSI lightcurve file
    - a RHESSI calibrated event list file.

I'm not sure if we still need these.

**Comment by ehsteve** [comment]
Are there enough AIA files to make a short (5 frame) movie?

**Comment by aringlis** [comment]
Not if you want to make a movie in time - there are currently 7 AIA images, each of a different channel. You could conceivably make a movie out of those.

**Comment by aringlis** [comment]
If you want an AIA temporal movie I suggest we add some cutout images, to keep the data smaller.

**Comment by ehsteve** [comment]
@aringlis that sounds like a good idea. should we do cutouts of the same time period so that you can see that in-falling material?

**Comment by ehsteve** [comment]
It would be good if one of the cutouts matched one of the larger frames, does that make sense?

**Comment by aringlis** [comment]
Agreed - let's do that.

**Comment by aringlis** [comment]
@ehsteve Done.

**Comment by ehsteve** [comment]
Would recommend adding fits to tca110607 and renaming the RecentIndices.txt file as well.

**Comment by aringlis** [comment]
@ehsteve I think this is ready now.

**Review by ehsteve — APPROVED** [review]

**Pull request merged**
