### PR TITLE
add roll image with rice compression

### LINKED ISSUE #30: Reduce the size of the roll image file
### Provide a general description of the issue or problem.

I think that if we download a fresh copy of the roll image file it would be rice compressed and that would end up being smaller than our gzip compressed current version. We will have to keep both versions around in the repo, but we should be able to reduce the total download size for new releases of sunpy.

### PR DESCRIPTION
**Pull request by nabobalis**
Fixes https://github.com/sunpy/sample-data/issues/30

TODO:

- [x] Downsample aia image from 2012
- [x] Add a script for doing it somewhere
- [x] Patch sunpy to use the new roll image for sample data (see https://github.com/sunpy/sunpy/pull/6221)

### CODE REVIEW

**Review by dstansby — CHANGES_REQUESTED** [review]
Just blocking this until we've check everything is working fine at https://github.com/sunpy/sunpy/pull/6221

**Review by dstansby — APPROVED** [review]
You can't just use `zoom` like this on the data without updating quite a bit of the FITS WCS metadata. `sunpy.GenericMap.resample()` should be used instead to automatically take care of the metadata changes.

**Review by dstansby — CHANGES_REQUESTED** [review]
my previous comment was not meant to be an approval...

**Comment by dstansby** [comment]
Here's an example (on the left) of what happens when the metadata isn't updated correctly:

sphx_glr_AIA_limb_STEREO_001

**Comment by nabobalis** [comment]
> You can't just use `zoom` like this on the data without updating quite a bit of the FITS WCS metadata. `sunpy.GenericMap.resample()` should be used instead to automatically take care of the metadata changes.

Fixed probably.

**Review by Cadair — APPROVED** [review]
I think this is fine, the sunpy gallery build appears to work.

**Review by dstansby — APPROVED** [review]

**Pull request merged**
