### PR TITLE
rice compress all the AIA sample data

### PR DESCRIPTION
**Pull request by Cadair**
This shrinks the files to about 950KB from 4.1M and compresses the cutouts to 1.4M from 3.2M

### CODE REVIEW

**Comment by nabobalis** [comment]
Do we have a script that allows other people to do the same on any data they want to submit?

**Comment by Cadair** [comment]
I am torn on if we should be changing this data in place like this. If you are just loading this through `sunpy.map.Map` then this will pose no issues, but it is moving the data from the primary HDU to the second HDU.

That being said doing this to AIA data does make it closer to the layout of the data JSOC provides. Opinions?

**Comment by Cadair** [comment]
script is:
```python
from pathlib import Path
from astropy.io import fits
import matplotlib.pyplot as plt
import sunpy.map


def compress_fits(infits, outfits):
    in_hdul = fits.open(str(infits))
    assert len(in_hdul) == 1, infits

    data = in_hdul[0].data
    header = in_hdul[0].header

    out_hdu = fits.CompImageHDU(data, header)

    out_hdul = fits.HDUList([fits.PrimaryHDU(), out_hdu])
    out_hdul.writeto(outfits, overwrite=True)




filenames = Path("/home/stuart/Git/sunpy-sample-data/sunpy/v1/")

for fname in filenames.glob("AIA*_cutout.fits"):
    compress_fits(fname, fname)

    m = sunpy.map.Map(str(fname))
    m.peek()
    plt.show()
```

**Comment by Cadair** [comment]
Ok, so I just looked at my AWS bill for last month. I am merging this.

**Pull request merged**
