### PR TITLE
Add STREO+AIA sample data

### PR DESCRIPTION
**Pull request by dstansby**
This has three files from when the two STEREO spacecraft and AIA were approximately equally spaced around the Sun.

### CODE REVIEW

**Comment by Cadair** [comment]
How big are these files in Mb ooi?

Long term I worry about having our sample data download take ages for people on limited connections.

**Comment by dstansby** [comment]
After compressing, they are 1.9MB, 2.1MB (STEREO) and 12.5MB (AIA). I could resample the AIA data down to say 1024 x 1024 to reduce that?

(p.s. I also force pushed to fix the LFS issues in an old commit)

**Review by nabobalis — APPROVED** [review]

**Comment by Cadair** [comment]
I think there is some merit in making this AIA image smaller, the situation before this PR where we only had one full resolution AIA image (the roll angle one) was a conscious choice.

**Comment by Cadair** [comment]
I think I shall take a look over the sizes of the files in the repo and see if there are any other changes I can make before I resample this new file. (looks at the roll image)

**Pull request merged**
