### PR TITLE
Replacing sample data files for the SunPy repository

### LINKED ISSUE #211: Normalize SunPy sample data
The current sample data for SunPy (e.g. sunpy.AIA_171_IMAGE, sunpy.RHESSI_IMAGE, etc) were chosen somewhat arbitrarily and have do not share anything in common.

I think it would be useful to take a more systematic approach to selecting sample data to include with SunPy.

Things to consider:
1. Choose data for same time period to allow for meaningful overlay and combination examples.
2. Decide which data sets should be included -- unless we decide we should have one sample image for each type of data supported, we should probably decide before-hand which types of data to include. Probably one sample image for each _type_ of data (disk image, coronagraph, single light-curve, multi-column lightcurve, etc) would be sufficient.
3. Since users will have to download all of these, make sure the files are relatively small.

### PR DESCRIPTION
**Pull request by aringlis**
The old SunPy sample files were from arbitrary dates and times. This PR replaces some of the old SunPy sample files, and replaces them with alternative files from the 2011-06-07 solar flare event. 

Not every file has been replaced - some of the old files should be ported into this repo.

closes sunpy/sunpy#211

### CODE REVIEW

**Comment by Cadair** [comment]
yeah we need to pull in all the old data as well.

**Review by Cadair — APPROVED** [review]

**Comment by Cadair** [comment]
is this just the data that isn't already in the sunpy sample data? Can you pull in the data which you want to keep in the 0.8 sample data, and I can pull in the whole 0.7 set later.

**Review by Cadair — CHANGES_REQUESTED** [review]
Needs to be a complete set of sample data for 0.8. (to close sunpy/sunpy#211)

**Comment by aringlis** [comment]
Yes, these are just the new files. I will pull in the old files that I want to keep as well.

**Comment by Cadair** [comment]
also @aringlis can you delete the first commit of this PR as it adds the files direct to git. (i.e. they are still in the history even though you lfs them afterwards).

**Pull request closed without merging**
